version: '3'

services:
  authapi:
    build:
      context: ./Auth-API
      dockerfile: Dockerfile
    environment:
      - dbPass=${dbPass}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - AUTHPORT=${AUTHPORT}
      - AUTH_TOKENSECRET=${AUTH_TOKENSECRET}
      - AUTH_REFRESH_TOKEN=${AUTH_REFRESH_TOKEN}
    container_name: AuthAPI
    ports:
      - 5000:5000
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
    - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./data/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      POSTGRES_PASSWORD: ${dbPass}
      POSTGRES_DB: auth
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - 6379:6379
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
volumes:
  mongodb_data: