# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install

# Rebuild bcrypt module
RUN npm rebuild bcrypt --build-from-source

# Copy the rest of the project files to the working directory
COPY . .

CMD ["npm", "start"]

# Set the command to start the application
EXPOSE 5000